version: 2
jobs:
  build:
    docker:
      - image: raviqqe/llvm-go
    working_directory: /go/src/github.com/raviqqe/jsonxx
    steps:
      - run: pacman -Syu --noconfirm rust
      - checkout
      - run:
          name: Install dependencies
          command: |
            go get -d -t ./...
            go get -u github.com/alecthomas/gometalinter
            $GOPATH/bin/gometalinter --install
      - run:
          name: Lint
          command: $GOPATH/bin/gometalinter --deadline 5m ./...
      - run:
          name: Build runtime
          command: |
            cd runtime
            make
      - run:
          name: Build command
          command: go build ./...
      - run:
          name: Test
          command: |
            go test -covermode atomic -coverprofile coverage.txt -race ./...
            curl -s https://codecov.io/bash | bash
