version: 2
jobs:
  build:
    docker:
      - image: base/archlinux
        environment:
          GOPATH: /go
    working_directory: /go/src/github.com/raviqqe/stg
    steps:
      - checkout
      - run: pacman -Syu --noconfirm base-devel cmake git go python subversion
      - run: go get -d -t ./...
      - run: $GOPATH/src/llvm.org/llvm/bindings/go/build.sh -DCMAKE_BUILD_TYPE=Release -DLLVM_PARALLEL_LINK_JOBS=1
      - run: go build ./...
      - run: go test -covermode atomic -coverprofile coverage.txt -race ./...
      - run: bash <(curl -s https://codecov.io/bash)
      - run: go get -u github.com/alecthomas/gometalinter
      - run: $GOPATH/bin/gometalinter --install
      - run: $GOPATH/bin/gometalinter ./...
