version: 2
jobs:
  build:
    docker:
      - image: raviqqe/llvm-go
    working_directory: /go/src/github.com/raviqqe/jsonxx
    steps:
      - run: pacman -Syu --noconfirm ruby-rake rust
      - checkout
      - run: rake
      - run: go get -d -t ./...
      - run: go get -u github.com/alecthomas/gometalinter
      - run: $GOPATH/bin/gometalinter --install
      - run: $GOPATH/bin/gometalinter --deadline 5m ./...
      - run: go build ./...
      - run: go test -covermode atomic -coverprofile coverage.txt -race ./...
      - run: curl -s https://codecov.io/bash | bash
